apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ritesh
  name: ritesh
  namespace: ritesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ritesh
  template:
    metadata:
      labels:
        app: ritesh
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.9.0
          name: mealie
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/data
              name: ritesh-data
      volumes:
        - name: ritesh-data
          persistentVolumeClaim:
            claimName: ritesh-data 

