apiVersion: v1
kind: Service
metadata:
  labels:
    app: ritesh
  name: ritesh
  namespace: ritesh
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: ritesh
  type: LoadBalancer
